trigger:
- master

pool:
  vmImage: windows-latest

variables:
  solution: src/RoslynPad.sln
  buildConfiguration: Release
  sdkVersion: 3.0.100-preview8-013656

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: $(sdkVersion)
  - script: dotnet msbuild /restore /bl /p:Configuration=$(buildConfiguration) $(solution)
    displayName: Build
