trigger:
- master

pool:
  vmImage: win1803

variables:
  solution: src/RoslynPad.sln
  buildConfiguration: Release
  sdkVersion: 3.0.100-preview5-011323

steps:
  - task: DotNetCoreInstaller@0
    inputs:
    version: $(sdkVersion)
  - script: dotnet msbuild /restore /bl /p:Configuration=$(buildConfiguration) $(solution)
    displayName: Build
