# Created with YamlCreate.ps1 v2.2.1 $debug=NVS0.CRLF.7-3-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: RoslynPad.RoslynPad
PackageVersion: 17.0.0
PackageLocale: en-US
Publisher: Eli Arbel
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: RoslynPad
# PackageUrl:
License: MIT
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: C# editor and runner based on Roslyn
# Description:
# Moniker:
# Tags:
# Agreements:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.2.0
